# -*- coding: utf-8 -*-
"""Generate version_info.txt (Windows VSVersionInfo) from app/version.py.

Usage:  python tools/make_version_info.py [output_path]

The version is read from app/version.py (single source of truth) so the
window title, About dialog, exe version resource and artifact names can
never drift apart.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATE = """# UTF-8
#
# Auto-generated by tools/make_version_info.py -- DO NOT EDIT.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vt},
    prodvers={vt},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [StringStruct('CompanyName', 'FXLibraryClient'),
           StringStruct('FileDescription', 'FX Library - UE5 FX asset library manager'),
           StringStruct('FileVersion', '{v4}'),
           StringStruct('InternalName', 'FXLibraryClient'),
           StringStruct('LegalCopyright', 'Copyright (c) 2026'),
           StringStruct('OriginalFilename', 'FXLibraryClient_v{ver}.exe'),
           StringStruct('ProductName', 'FX Library'),
           StringStruct('ProductVersion', '{v4}')])
      ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def read_version():
    path = os.path.join(ROOT, "app", "version.py")
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    m = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', src)
    if not m:
        raise SystemExit("ERROR: __version__ not found in app/version.py")
    return m.group(1)


def main():
    ver = read_version()
    parts = [int(x) for x in ver.split(".") if x.isdigit()]
    while len(parts) < 4:
        parts.append(0)
    vt = tuple(parts[:4])
    v4 = ".".join(str(x) for x in vt)
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "version_info.txt")
    text = TEMPLATE.format(vt=vt, v4=v4, ver=ver)
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    print("version=%s -> %s" % (ver, out))


if __name__ == "__main__":
    main()
